export const mockNews = {
        tech: [
    {
        id: "1",
        headline: "NVIDIA launches next-generation AI chip",
        source: "TechCrunch",
        published_at: "2026-04-16T09:00:00Z",
        sector: "tech",
    },
    {
        id: "2",
        headline: "Apple reveals new mixed reality headset",
        source: "The Verge",
        published_at: "2026-04-16T07:30:00Z",
        sector: "tech",
    },
    {
        id: "3",
        headline: "Google introduces new Gemini update",
        source: "Wired",
        published_at: "2026-04-16T06:10:00Z",
        sector: "tech",
    },
    {
        id: "4",
        headline: "Microsoft expands AI tools in Office",
        source: "CNBC",
        published_at: "2026-04-16T04:50:00Z",
        sector: "tech",
    },
    {
        id: "5",
        headline: "Open-source robotics startup raises funding",
        source: "VentureBeat",
        published_at: "2026-04-16T03:20:00Z",
        sector: "tech",
    },
    ],
    finance: [
    {
        id: "6",
        headline: "Federal Reserve signals possible rate cut",
        source: "Bloomberg",
        published_at: "2026-04-16T08:15:00Z",
        sector: "finance",
    },
    {
        id: "7",
        headline: "Gold prices surge as investors seek safer assets",
        source: "Reuters",
        published_at: "2026-04-16T07:40:00Z",
        sector: "finance",
    },
    {
        id: "8",
        headline: "JP Morgan reports stronger-than-expected earnings",
        source: "CNBC",
        published_at: "2026-04-16T06:50:00Z",
        sector: "finance",
    },
    {
        id: "9",
        headline: "Cryptocurrency market rebounds after recent sell-off",
        source: "Forbes",
        published_at: "2026-04-16T05:25:00Z",
        sector: "finance",
    },
    {
        id: "10",
        headline: "RBI introduces new digital payment guidelines",
        source: "Economic Times",
        published_at: "2026-04-16T04:10:00Z",
        sector: "finance",
    },
    ],
    business: [
        {
            id: "11",
            headline: "Amazon expands into African logistics market",
            source: "Reuters",
            published_at: "2026-04-16T06:00:00Z",
            sector: "business",
        },
        {
            id: "12",
            headline: "Tesla opens new manufacturing plant in Mexico",
            source: "Business Insider",
            published_at: "2026-04-16T05:30:00Z",
            sector: "business",
        },
        {
            id: "13",
            headline: "Starbucks announces global price increase",
            source: "Wall Street Journal",
            published_at: "2026-04-16T04:45:00Z",
            sector: "business",
        },
        {
            id: "14",
            headline: "Walmart acquires regional e-commerce startup",
            source: "CNBC",
            published_at: "2026-04-16T03:50:00Z",
            sector: "business",
        },
        {
            id: "15",
            headline: "Airbnb reports record bookings for summer season",
            source: "Financial Times",
            published_at: "2026-04-16T02:35:00Z",
            sector: "business",
        },
    ],
    health: [
    {
        id: "16",
        headline: "WHO approves new vaccine strategy",
        source: "BBC",
        published_at: "2026-04-16T05:00:00Z",
        sector: "health",
    },
    {
        id: "17",
        headline: "Researchers develop AI tool for cancer detection",
        source: "Nature",
        published_at: "2026-04-16T04:20:00Z",
        sector: "health",
    },
    {
        id: "18",
        headline: "India launches nationwide diabetes prevention campaign",
        source: "The Hindu",
        published_at: "2026-04-16T03:40:00Z",
        sector: "health",
    },
    {
        id: "19",
        headline: "Pfizer begins trials for next-generation flu vaccine",
        source: "Reuters",
        published_at: "2026-04-16T02:50:00Z",
        sector: "health",
    },
    {
        id: "20",
        headline: "Hospitals adopt wearable devices for remote monitoring",
        source: "Healthline",
        published_at: "2026-04-16T01:30:00Z",
        sector: "health",
    },
    ],
};